name: GitHub CI

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  black-test:
    name: Black Python code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install black
        run: pip install "black[jupyter]"
      - name: Ensure contributor used ("black ./") before commit
        run: black --check ./